name: CI/CD for BE

on:
  push:
    branches:
      - be/dev

jobs:
  setup-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create env file
        run: |

      - name: Copy .env to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "./capstone-project-be/docker-compose.yml"
          target: "capstone"

      - name: Copy docker-compose.yaml to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "./capstone-project-be/docker-compose.yml"
          target: "capstone"

  build-back:
    name: Build & Push Spring Boot (back)
    runs-on: ubuntu-latest
    needs: setup-env

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant Gradle permission
        run: chmod +x ./capstone-project-be/back/gradlew 

      - name: Build back project
        working-directory: ./capstone-project-be/back
        run: ./gradlew clean build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Dockerhub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push docker image (back) to dockerhub
        uses: docker/build-push-action@v6
        with:
          context: ./capstone-project-be/back
          push: true
          tags: ${{ secrets.DOCKER_REPO }}/back:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-gateway:
    name: Build & Push Spring Cloud Gateway
    runs-on: ubuntu-latest
    needs: setup-env

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant Gradle permission
        run: chmod +x ./capstone-project-be/gateway/gradlew

      - name: Build gateway project
        working-directory: ./capstone-project-be/gateway
        run: ./gradlew clean build

      - name: Dockerhub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push docker image (gateway) to dockerhub
        uses: docker/build-push-action@v6
        with:
          context: ./capstone-project-be/gateway
          push: true
          tags: ${{ secrets.DOCKER_REPO }}/back:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy to EC2 via Docker Compose
    needs: [setup-env, build-back, build-gateway]
    runs-on: ubuntu-latest

    steps:
      - name: Connect & Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            if [ "$(sudo docker ps -qa)" ]; then
              sudo docker rm -f $(sudo docker ps -qa)
            
            fi
            
            sudo docker pull ${{ secrets.DOCKER_REPO }}/back
            sudo docker pull ${{ secrets.DOCKER_REPO }}/gateway
            sudo docker-compose -f ~/capstone/docker-compose.yml up -d --remove-orphans
            sudo docker image prune -f
