name: CI/CD for BE

on:
  push:
    branches:
      - be/dev

jobs:
  setup-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create env file
        run: |
          echo DATASOURCE_URL=${{ secrets.DATASOURCE_URL }} >> .env
          echo DATASOURCE_USERNAME=${{ secrets.DATASOURCE_USERNAME }} >> .env
          echo DATASOURCE_PASSWORD=${{ secrets.DATASOURCE_PASSWORD }} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
          echo JWT_EXP=${{ secrets.JWT_EXP }} >> .env
          echo AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }} >> .env
          echo AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }} >> .env
          echo S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }} >> .env
          echo ANOMALY_URL=${{ secrets.ANOMALY_URL }} >> .env
          echo LLM_URL=${{ secrets.LLM_URL }} >> .env

      - name: Copy .env to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "./.env"
          target: "capstone"

      - name: Copy docker-compose.yaml to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "./capstone-project-be/docker-compose.yml"
          target: "capstone"

  build-back:
    name: Build & Push Spring Boot (back)
    runs-on: ubuntu-latest
    needs: setup-env

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant Gradle permission
        run: chmod +x ./capstone-project-be/back/gradlew 

      - name: Build back project
        working-directory: ./capstone-project-be/back
        run: ./gradlew clean build -x test
        env:
          DATASOURCE_URL: ${{ secrets.DATASOURCE_URL }}
          DATASOURCE_USERNAME: ${{ secrets.DATASOURCE_USERNAME }}
          DATASOURCE_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Dockerhub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push docker image (back) to dockerhub
        uses: docker/build-push-action@v6
        with:
          context: ./capstone-project-be/back
          push: true
          tags: ${{ secrets.DOCKER_REPO }}/2025-capstone-spring:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-gateway:
    name: Build & Push Spring Cloud Gateway
    runs-on: ubuntu-latest
    needs: setup-env

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant Gradle permission
        run: chmod +x ./capstone-project-be/gateway/gradlew

      - name: Build gateway project
        working-directory: ./capstone-project-be/gateway
        run: ./gradlew clean build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Dockerhub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push docker image (gateway) to dockerhub
        uses: docker/build-push-action@v6
        with:
          context: ./capstone-project-be/gateway
          push: true
          tags: ${{ secrets.DOCKER_REPO }}/2025-capstone-gateway:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy to EC2 via Docker Compose
    needs: [setup-env, build-back, build-gateway]
    runs-on: ubuntu-latest

    steps:
      - name: Connect & Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            if [ "$(sudo docker ps -qa)" ]; then
              sudo docker rm -f $(sudo docker ps -qa)
            
            fi
            
            sudo docker pull ${{ secrets.DOCKER_REPO }}/2025-capstone-spring:latest
            sudo docker pull ${{ secrets.DOCKER_REPO }}/2025-capstone-gateway:latest
            sudo docker-compose -f ~/capstone/docker-compose.yml up -d --remove-orphans
            sudo docker image prune -f
